name: Deploy Project
on: [push, workflow_dispatch]  #push changed to allow manual trigger too, workflow_dispatch allows manual trigger
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code #donwload the code from github repository on the runner (server) which could be in github cloud
              uses: actions/checkout@v3 #reserved word to run an action, is different from run
            - name: Install NodeJs  #this step it is not necessary, because this runner already has nodejs installed by defau
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Install Dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
      needs: test  #this job will run only if the test job is successful, if it was dependding on more than one, it would be [test, anotherJob]
      runs-on: ubuntu-latest  #every job runs on a different runner
      steps:
        - name: Get Code
          uses: actions/checkout@v3
        - name: Install NodeJs
          uses: actions/setup-node@v3
          with:
            node-version: '18'
        - name: Install Dependencies
          run: npm ci
        - name: Build Project
          run: npm run build
        - name: Deploy
          run: echo "Deploying"