name: Output information
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github Context
              run: echo "${{ toJSON(github) }}" #allows to access to github metadata dinamically